### ISSUE TITLE
PNG kernel export

### ISSUE THREAD

**Issue by j-beyer** [p-otto/glkernel#18]
using libpng,
evaluate whether tinypng compression is feasible here

**Comment by cgphilipp** [comment]
See #4

**Comment by cgphilipp** [comment]
We want to support different internal png formats, depending on what libpng offers.
This should be respected by the -f flag of the CLI.

**Comment by j-beyer** [comment]
Evaluate the existing architecture (generic KernelExporter interface, object methods vs static methods vs non-class methods)

**Comment by j-beyer** [comment]
Scale float range to int range 0-16bit,
write scaling factor to file
