### ISSUE TITLE
gather and discuss c++ ways for 2nd kernel interface

### ISSUE THREAD

**Issue by cgcostume** [p-otto/glkernel#3]
Instead of 
```
auto screendoor_alpha = kernel1{ 8, 8 };
sequence::uniform(screendoor_alpha, epsilon, 1.f - epsilon);
shuffle::bucket_permutate(screendoor_alpha, 4, 4);
```
the kernel should also support something like
```
auto screendoor_alpha = kernel1{ 8, 8 };
screendoor_alpha.sequence.uniform(epsilon, 1.f - epsilon).shuffle.bucket_permutate(4, 4);
```
I'm yet not sure if this is something we really need.

**Comment by cgphilipp** [comment]
A language feature like this was proposed by Bjarne Stroustrup, see https://isocpp.org/blog/2016/02/a-bit-of-background-for-the-unified-call-proposal. Free functions standing in for member functions, as would be required for this feature, have later been excluded from the proposal after heavy negative feedback.

The ways I see to implement this include lots of maintenance overhead or code generation. I do not like either version.

Anyone have other ideas for this?
