### ISSUE TITLE
Split up destination locations of JSInterface and glkernel.js

### ISSUE THREAD

**Issue by j-beyer** [p-otto/glkernel#58]
Similar to the handling of e.g. shaders in other graphics libraries, we suppose to generate the `glkernel.js` API into the glkernel/data directory.
At the same time, we need JSinterface.cpp and JSInterface.h to be located in the source directory.

Suggestions:
- Adapt the destination logic in the python script to
  - take another parameter for the js destination dir
  - always generate the js file into the data/ directory
- Add a cmake command that simply moves the js file to data/ after generation

**Comment by Tobias1595** [comment]
Done, see d1c2586
