### ISSUE TITLE
gather relevant info on SIMD and omp parallel w.r.t. kernel processing

### ISSUE THREAD

**Issue by cgcostume** [p-otto/glkernel#6]
Find and discuss ways for optimizations on kernel generation procedures as well as transformations. Whenever for every cell and every component of each cell a value is to be computed, various parallelization approaches might be applicable. E.g. SIMD for components, omp for cells.

**Comment by cgcostume** [comment]
In addition to this, SIMD could also be used to optimize cell optimization, e.g. for one and two component vectors SIMD for cell parallelization could applied in addition to CPU paralell...

**Comment by cgcostume** [comment]
For it, various iterators should be provided. All optimizations should be benchmarked against non-parallel and partial-parallel execution.

**Comment by cgcostume** [comment]
with respect to omp and simd this might be a starting point:
[omp for simd](https://software.intel.com/en-us/node/524522), [omp parallel for](https://software.intel.com/en-us/node/524526), [omp parallel for simd](https://software.intel.com/en-us/node/524527).

**Comment by Beta-Alf** [comment]
This issue is part of a larger issue set. The other issues deal with:
- [x]  Benchmarks #
- [x]  OMP
- [ ]  SIMD

**Comment by Beta-Alf** [comment]
Moving this back to Milestone 3 since it is encompassing features from Milestone 1-3

**Comment by Beta-Alf** [comment]
Benchmarks and OMP are working. SIMD was discontinued.
