### ISSUE TITLE
plan and discuss refined compiler output for template mismatch/missing implementations

### ISSUE THREAD

**Issue by cgcostume** [p-otto/glkernel#7]
This issue should be used to gather information on how glkernel could communicate missing implementations for requested kernel processing of specific kernel dimensions (1D, 2D, 3D, nD), cell-types (float, double, ...), and number of components per cell (vec1, vec2, vec3, vec4?).

**Comment by Beta-Alf** [comment]
A good first starting point could be [static assert](http://en.cppreference.com/w/cpp/language/static_assert).
